language: java
sudo: false
jdk:
  - openjdk6
  - oraclejdk7
cache:
  directories:
    - $HOME/idea
    - $HOME/.ant
    - $HOME/.ivy2
env:
  - IDEA_VERSION=14.1.4
before_install:
  - pip install --user codecov
install:
  - IDEA_TAR=ideaIC-${IDEA_VERSION}.tar.gz
  - IDEA_PARENT_DIR=$HOME/idea
  - IDEA_DIR=$IDEA_PARENT_DIR/$IDEA_VERSION
  - |
    echo "Acquiring Intellij IDEA"
    if [ -d $IDEA_DIR ]; then
        echo "Using existing Intellij IDEA installation at $IDEA_DIR"
    else
        echo "Removing existing Intellij IDEA installation"
        rm -rf $IDEA_PARENT_DIR
        mkdir -p $IDEA_PARENT_DIR
        echo "Downloading Intellij IDEA archive"
        travis_retry wget http://download.jetbrains.com/idea/$IDEA_TAR -P $HOME
        echo "Installing Intellij IDEA to $IDEA_DIR"
        tar xzvf $HOME/$IDEA_TAR -C $IDEA_PARENT_DIR
        mv $IDEA_PARENT_DIR/idea-IC-* $IDEA_DIR
    fi
  - echo "idea.home=$IDEA_DIR" >> build.properties
  - ant resolve
script: ant
after_success:
  - codecov
